###
# ____________________________ Authentication ____________________________

###
# login
POST http://localhost:5000/login 
Content-Type: application/json

{
    "email": "test123@mail.com",
    "password": "12345678"
}

###

# ____________________________ USERS ____________________________
# create users only requied fields
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "username_test",
    "firstname":"firstname_test",
    "lastname":"lastname_test",
    "email": "test123@mail.com",
    "password": "12345678",
    "confirmpassword": "12345678"
}
###


###
# get all users
GET http://localhost:5000/users HTTP/1.1
###

###
# change Password
PUT http://localhost:5000/users/changepassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIzN2ViYWRiOWY2ZDBkNWMzN2I3MTEiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NDY1ODYyMDB9.GNeUognnUdkqUez-TCG6iSQtBLXvwHIAHm1OP3ZeIQg
Content-Type: application/json

{
    "oldPassword": "12345678",
    "newPassword": "123456789",
    "confirmNewPassword": "123456789"
}
###
# send email newPassword
POST http://localhost:5000/users/resetpassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI1MTU4OTIxODY2MTE4NTBkZDc2ZDMiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NDY1OTc1Mzl9.yw4gpU7qJHsjQDS0DFqahfn_sb4u9xKEZYH3OGuxmfU
Content-Type: application/json

{
    "email": "zioqzpqrrzzahktysg@bvhrk.com"
}
###
# new password
PUT http://localhost:5000/users/newpassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI1MTU4OTIxODY2MTE4NTBkZDc2ZDMiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NDY1OTc1Mzl9.yw4gpU7qJHsjQDS0DFqahfn_sb4u9xKEZYH3OGuxmfU
Content-Type: application/json

{
    "newPassword": "123456789",
    "confirmNewPassword": "123456789"
}

###
# get only one user
GET http://localhost:5000/users/622515892186611850dd76d3 HTTP/1.1
###
###
# get check is mentor
GET http://localhost:5000/users/role/62210331e4339c1e71363587 HTTP/1.1
###

# get all mentors
GET http://localhost:5000/users/mentors HTTP/1.1

###
# EDIT USER
PATCH  http://localhost:5000/users/edit HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6Ik1lbnRvciBKYXZhIiwiaWF0IjoxNjUyMjIxNDMyfQ.NQR1ZQXZlLvFtR-qPZaastS8K7vrZ1aZI99al8_60sU
Content-Type: application/json

{
    "firstname": "Edit user",
    "lastname": "Gosia last 2",
    "isMentor": true
}

###
# EDIT USER LANGUAGES
PATCH  http://localhost:5000/users/lang HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6Ik1lbnRvciBKYXZhIiwiaWF0IjoxNjUyMjIxNDMyfQ.NQR1ZQXZlLvFtR-qPZaastS8K7vrZ1aZI99al8_60sU
Content-Type: application/json

{
    "programmingLanguage":[
        {
            "nameLang": "python",
            "level": "junior"
        },
        {
            "nameLang": "c++",
            "level": "senior"
        }
    ]
}

### DELETE USER
DELETE http://localhost:5000/users HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyODY1MWY0YzAxMzU3YTBlMGZkYzMiLCJ1c2VybmFtZSI6InVzZXJuYW1lX3Rlc3QiLCJpYXQiOjE2NTI3MjEyODV9.ift1xE2egi6Ta8RI-FIWfpatFaKiy5wDVB5HlGVjN-k

###
# ____________________________ TEAM ____________________________
POST http://localhost:5000/team/create HTTP/1.1
Content-Type: application/json

{
    "teamName": "Team Node 2",
    "usersIds": [],
    "mentorId": "62210331e4339c1e71363587",
    "programmingLanguage": [
        {
         "nameLang": "node",
        "level": "beginner"
        }
    ],
    "status": true,
    "places": 10,
    "description": "Only learn node"
}
###
GET http://localhost:5000/team HTTP/1.1
###
GET http://localhost:5000/team/6235fa33621d817289f6e462 HTTP/1.1
###
PUT http://localhost:5000/team/62278e3a7cafabc04f5cbeab HTTP/1.1
Content-Type: application/json

{
    "teamName": "Ftr",
    "usersIds": ["621d35383e5c3315845ca334"],
    "programmingLanguage": [
        {
         "nameLang": "javaeeee",
        "level": "jhjh"
        }
    ],
    "status": true
}
###
DELETE http://localhost:5000/team/62278e3a7cafabc04f5cbeab HTTP/1.1
###
#Join Team
PUT http://localhost:5000/team/join/627fe4230c1e381902817114 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjgyODY1MWY0YzAxMzU3YTBlMGZkYzMiLCJ1c2VybmFtZSI6InVzZXJuYW1lX3Rlc3QiLCJpYXQiOjE2NTI3MjEzMTR9.veJKBT7UhehhumgO3Nt0JTuzdCjsmpT2jhYaDSlMkYE
Content-Type: application/json

###
# user Teams
GET http://localhost:5000/team/user-team HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI1MTU4OTIxODY2MTE4NTBkZDc2ZDMiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NTA4MTQxOTJ9.RH85bFJ2pdBj0sflcdjv7VulTXb84TbbfHDKaxoic10
Content-Type: application/json

###
# ____________________________ PROJECT ____________________________

# GET ALL PROJECTS 
GET http://localhost:5000/project

###
# GET PROJECT BY ID
GET http://localhost:5000/project/627fad94e81a482fa09171b3

###
# GET USER PROJECTS
GET http://localhost:5000/project/user-projects
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjdmYWM3N2U4MWE0ODJmYTA5MTcxYjIiLCJ1c2VybmFtZSI6InVzZXJuYW1lX3Rlc3QiLCJpYXQiOjE2NTI1MzQ2ODR9.ih30QFkeHqX3fSrxUnMZsSm3qjBG8Zf7iSBoVLIORvI

###
# CREATE PROJECT
POST http://localhost:5000/project/create
Content-Type: application/json

{
	"name": "Projekt23",
	"userId": "627fac77e81a482fa09171b2",
	"mentorId": "62210331e4339c1e71363587",
	"content": "aplikacja",
    "language": ["JavaScript", "Python"],
    "description": "awesome project!"
}

###
# EDIT PROJECT
PUT http://localhost:5000/project/626d019cb513693f389a0c75
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6Ik1lbnRvciBKYXZhIiwiaWF0IjoxNjUxMDkxMjc4fQ.8Rejdd8TNbfQkqoQ6bGo_msccy9ZrvEhVAEY-h_9ADk
Content-Type: application/json

{
	"name": "Super Project!!!",
	"content": "Gitlab",
    "status": "closed",
    "description": "Projekt Roku!",
    "language": ["TypeScript", "GO"],
}

###
# EDIT PROJECT'S MEMBERS 
# teamId : objectID | null
# mentorId : objectID | null
# userId : objectID | null
PUT http://localhost:5000/project/members/626d019cb513693f389a0c75
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6Ik1lbnRvciBKYXZhIiwiaWF0IjoxNjUxMDkxMjc4fQ.8Rejdd8TNbfQkqoQ6bGo_msccy9ZrvEhVAEY-h_9ADk
Content-Type: application/json

{
	"teamId": "6264facc175f012d595a1ef3"
}

###
# DELETE PROJECT
DELETE http://localhost:5000/project/626d019cb513693f389a0c75
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6Ik1lbnRvciBKYXZhIiwiaWF0IjoxNjUxMDkxMjc4fQ.8Rejdd8TNbfQkqoQ6bGo_msccy9ZrvEhVAEY-h_9ADk

###
# ____________________________ OPINIONS ____________________________

###
# GET OPINIONS
GET http://localhost:5000/opinion

###
# GET OPINION
GET http://localhost:5000/opinion/6282907fb062064904f7e73f

###
# CREATE OPINION
POST http://localhost:5000/opinion/create
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6InQ1NXR0IiwiaWF0IjoxNjUyNzIyNTUxfQ.i8GDCMz-M0LtJsimJ0U9sE0k2P5qZty0uDnmbSJISrU
Content-Type: application/json

{
    "userId": "62210331e4339c1e71363587",
    "mentorId": "622101a32be5811d66abde97",
    "content": "Opinia pięciogwiazdkowa",
    "stars": "5"
}

###
# EDIT OPINION
PUT http://localhost:5000/opinion/edit/6282907fb062064904f7e73f
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6InQ1NXR0IiwiaWF0IjoxNjUyNzIyNTUxfQ.i8GDCMz-M0LtJsimJ0U9sE0k2P5qZty0uDnmbSJISrU
Content-Type: application/json

{
    "content": "Opinia czterogwiadkowa",
    "stars": "4"
}

# DELETE OPINION
DELETE http://localhost:5000/opinion/6282907fb062064904f7e73f
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6InQ1NXR0IiwiaWF0IjoxNjUyNzIyNTUxfQ.i8GDCMz-M0LtJsimJ0U9sE0k2P5qZty0uDnmbSJISrU

###
# ____________________________ NOTIFICATIONS ____________________________

# GET NOTIFICATIONS
GET http://localhost:5000/notification
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6InQ1NXR0IiwiaWF0IjoxNjUyNzM3NjQzfQ._hyMmWVVyeZPZG-SsKsRBThcaX_VM7cVhMXcEDaD1C0

###
# SEND NOTIFICATION
POST http://localhost:5000/notification/send
Content-Type: application/json

{
    "userId": "62210331e4339c1e71363587",
    "text": "dodano do zespołu"
}

###
# CHANGE NOTIFICATION STATUS ON READ
PUT http://localhost:5000/notification/change/6282d303fb49a25ab47f43ef
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6InQ1NXR0IiwiaWF0IjoxNjUyNzM3NjQzfQ._hyMmWVVyeZPZG-SsKsRBThcaX_VM7cVhMXcEDaD1C0

###
# CLEAR NOTIFICATIONS (Change all notification's statuses on read)
PUT http://localhost:5000/notification/clear
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6InQ1NXR0IiwiaWF0IjoxNjUyNzM3NjQzfQ._hyMmWVVyeZPZG-SsKsRBThcaX_VM7cVhMXcEDaD1C0

###
# DELETE NOTIFICATION
DELETE  http://localhost:5000/notification/6282d2f9fb49a25ab47f43ee
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIxMDMzMWU0MzM5YzFlNzEzNjM1ODciLCJ1c2VybmFtZSI6InQ1NXR0IiwiaWF0IjoxNjUyNzM3NjQzfQ._hyMmWVVyeZPZG-SsKsRBThcaX_VM7cVhMXcEDaD1C0
