###
# ____________________________ Authentication ____________________________

###
# login
POST http://localhost:5000/login 
Content-Type: application/json

{
    "email": "zioqzpqrrzzahktysg@bvhrk.com",
    "password": "123456789"

}

###

# ____________________________ USERS ____________________________
# create users only requied fields
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "username_test",
    "firstname":"firstname_test",
    "lastname":"lastname_test",
    "email": "test@mail.com",
    "password": "12345678",
    "confirmpassword": "12345678"
}
###


###
# get all users
GET http://localhost:5000/users HTTP/1.1
###

###
# change Password
PUT http://localhost:5000/users/changepassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIzN2ViYWRiOWY2ZDBkNWMzN2I3MTEiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NDY1ODYyMDB9.GNeUognnUdkqUez-TCG6iSQtBLXvwHIAHm1OP3ZeIQg
Content-Type: application/json

{
    "oldPassword": "12345678",
    "newPassword": "12345678",
    "confirmNewPassword": "12345678"
}
###
# send email newPassword
POST http://localhost:5000/users/resetpassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI1MTU4OTIxODY2MTE4NTBkZDc2ZDMiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NDY1OTc1Mzl9.yw4gpU7qJHsjQDS0DFqahfn_sb4u9xKEZYH3OGuxmfU
Content-Type: application/json

{
    "email": "zioqzpqrrzzahktysg@bvhrk.com"
}
###
# new password
PUT http://localhost:5000/users/newpassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI1MTU4OTIxODY2MTE4NTBkZDc2ZDMiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NDY1OTc1Mzl9.yw4gpU7qJHsjQDS0DFqahfn_sb4u9xKEZYH3OGuxmfU
Content-Type: application/json

{
    "newPassword": "123456789",
    "confirmNewPassword": "123456789"
}

###
# get only one user
GET http://localhost:5000/users/621d35383e5c3315845ca334 HTTP/1.1
###
###
# get check is mentor
GET http://localhost:5000/users/role/62239d63a5182b274496ee34 HTTP/1.1
###
# get check is mentor
PATCH  http://localhost:5000/users/62239d63a5182b274496ee34 HTTP/1.1
Content-Type: application/json

{
    "username": "t55tt",
    "firstname": "Edit user",
    "lastname": "Gosia last",
    "email": "test@test.xyz",
    "isMentor": true
}
###
# ____________________________ TEAM ____________________________
POST http://localhost:5000/team/create HTTP/1.1
Content-Type: application/json

{
    "teamName": "Team38ya",
    "usersIds": ["622b9441f2950d6fe0a2b40c", "4edd40c86762e0fb12000003"],
    "mentorId": "62239d63a5182b274496ee34",
    "programmingLanguage": [
        {
         "nameLang": "javaeeee",
        "level": "jhjh"
        }
    ],
    "status": true
}
###
GET http://localhost:5000/team HTTP/1.1
###
GET http://localhost:5000/team/6235fa33621d817289f6e462 HTTP/1.1
###
PUT http://localhost:5000/team/62278e3a7cafabc04f5cbeab HTTP/1.1
Content-Type: application/json

{
    "teamName": "Ftr",
    "usersIds": ["621d35383e5c3315845ca334"],
    "programmingLanguage": [
        {
         "nameLang": "javaeeee",
        "level": "jhjh"
        }
    ],
    "status": true
}
###
DELETE http://localhost:5000/team/62278e3a7cafabc04f5cbeab HTTP/1.1
###

# ____________________________ PROJECT____________________________
# create Project
POST http://localhost:5000/project/create
Content-Type: application/json

{
	"name": "Projekt ja22282",
	"userId": "622b9441f2950d6fe0a2b40e",
    "mentorId": "", 
	"content": "aplikacja",
    "status": "true"
}
###
# edit Project
PUT http://localhost:5000/project/6235f9b909fe6e1c88fde621
Content-Type: application/json

{
	"name": "Zmieniona nazwa",
	"userId": "4edd40c86762e0fb12000003",
	"mentorId": "fcee56c86762e0fb12000112",
	"content": "Dodany mentor"
}
###
# get all Project
GET http://localhost:5000/project/

###
# delete Project
DELETE http://localhost:5000/project/622b96d05564155028570b45


###
# ____________________________TEAM PROJECT ____________________________

###
# ____________________________ OPINIONS ____________________________
# create opinion
POST http://localhost:5000/opinion/create
Content-Type: application/json

{
    "userId": "4edd40c86762e0fb12000005",
    "mentorId": "fcee56c86762e0fb12000112",
    "content": "Opinia pięciogwiazdkowa",
    "stars": "4"
}
###
# edit opinion
PUT http://localhost:5000/opinion/edit
Content-Type: application/json

{
    "content": "Opinia czterogwiadkowa"
}
###
#
# DELETE http://localhost:5000/opinion/delete

DELETE http://localhost:5000/opinion/

###
# get one opinion
GET http://localhost:5000/opinion/6234f97af8b4d700ef698542

###
# get all opinions
GET http://localhost:5000/opinion
