###
# ____________________________ Authentication ____________________________

###
# login
POST http://localhost:5000/login 
Content-Type: application/json

{
    "email": "ania@test.com",
    "password": "12345678"

}

###

# ____________________________ USERS ____________________________
# create users only requied fields
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "firstname":"test firstname",
    "lastname":"test last name",
    "email": "marta.anna.probierz@gmail.com",
    "password": "12345678"
}
###


###
# get all users
GET http://localhost:5000/users HTTP/1.1
###

###
# change Password
PUT http://localhost:5000/users/changepassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjIzN2ViYWRiOWY2ZDBkNWMzN2I3MTEiLCJ1c2VybmFtZSI6IkFuaWEiLCJpYXQiOjE2NDY1ODYyMDB9.GNeUognnUdkqUez-TCG6iSQtBLXvwHIAHm1OP3ZeIQg
Content-Type: application/json

{
    "oldPassword": "12345678",
    "newPassword": "12345678",
    "confirmNewPassword": "12345678"
}


###
# get only one user
GET http://localhost:5000/users/621d35383e5c3315845ca334 HTTP/1.1
###
###
# get check is mentor
GET http://localhost:5000/users/role/62239d63a5182b274496ee34 HTTP/1.1
###
# get check is mentor
PATCH  http://localhost:5000/users/62239d63a5182b274496ee34 HTTP/1.1
Content-Type: application/json

{
    "username": "t55tt",
    "firstname": "Edit user",
    "lastname": "Gosia last",
    "email": "test@test.xyz",
    "isMentor": true,
}
###
# ____________________________ TEAM ____________________________

###
# ____________________________ PROJECT ____________________________

###
# ____________________________TEAM PROJECT ____________________________

###
# ____________________________ OPINIONS ____________________________
# create opinion
POST http://localhost:5000/opinion/create
Content-Type: application/json

{
    "name": "opinia testowa 123",
    "userId": "4edd40c86762e0fb12000003",
    "mentorId": "fcee56c86762e0fb12000112",
    "content": "Opinia pięciogwiadkowa"
}
###
# edit opinion
PUT http://localhost:5000/opinion/edit
Content-Type: application/json

{
    "name": "opinia testowa 123",
    "userId": "4edd40c86762e0fb12000004",
    "mentorId": "fcee56c86762e0fb12000112",
    "content": "Opinia czterogwiadkowa"
}
###
#
# DELETE http://localhost:5000/opinion/delete

DELETE http://localhost:5000/opinion/

###
# get one opinion
GET http://localhost:5000/opinion/6234f97af8b4d700ef698542

###
# get all opinions
GET http://localhost:5000/opinion